# Generated by Django 4.0 on 2024-06-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='produit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DigitalWaves.produit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panier',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
